export default {
  version: '1.0.0',
  contractName: 'PalmeraGuard',
  defaultAddress: '0xDC3b09F050e6e589DAF11Fb949DBA4Af3d2089B6',
  abi: [
    {
      inputs: [{ internalType: 'address', name: 'palmeraModuleAddr', type: 'address' }],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'ArrayOfModulesEmpty', type: 'error' },
    {
      inputs: [{ internalType: 'address', name: 'guard', type: 'address' }],
      name: 'CannotDisablePalmeraGuard',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'address', name: 'module', type: 'address' }],
      name: 'CannotDisablePalmeraModule',
      type: 'error',
    },
    { inputs: [], name: 'InvalidAddressProvided', type: 'error' },
    { inputs: [], name: 'InvalidModuleProvided', type: 'error' },
    { inputs: [], name: 'NotAuthorizedAsNotRootOrSuperSafe', type: 'error' },
    { inputs: [], name: 'NotAuthorizedAsNotSafeLead', type: 'error' },
    { inputs: [], name: 'NotAuthorizedEnableExternalModule', type: 'error' },
    {
      inputs: [],
      name: 'NotAuthorizedPalmeraModuleMustBeFirst',
      type: 'error',
    },
    { inputs: [], name: 'NotPermittedReceiveEther', type: 'error' },
    { inputs: [], name: 'UserAlreadyOnList', type: 'error' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'address[]',
          name: 'modules',
          type: 'address[]',
        },
      ],
      name: 'AddedExternalModuleToList',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'module',
          type: 'address',
        },
      ],
      name: 'DroppedExternalModuleFromList',
      type: 'event',
    },
    { stateMutability: 'nonpayable', type: 'fallback' },
    {
      inputs: [],
      name: 'NAME',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'VERSION',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address[]', name: 'modules', type: 'address[]' },
      ],
      name: 'addToModulesList',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'allowFeature',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: '', type: 'bytes32' },
        { internalType: 'bool', name: '', type: 'bool' },
      ],
      name: 'checkAfterExecution',
      outputs: [],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'bytes', name: 'data', type: 'bytes' },
        { internalType: 'enum Enum.Operation', name: '', type: 'uint8' },
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address payable', name: '', type: 'address' },
        { internalType: 'bytes', name: '', type: 'bytes' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'checkTransaction',
      outputs: [],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'denyFeature',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'module', type: 'address' },
      ],
      name: 'dropFromModulesList',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: 'org', type: 'bytes32' }],
      name: 'emptyModulesList',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'wallet', type: 'address' },
      ],
      name: 'getPrevUser',
      outputs: [{ internalType: 'address', name: 'prevUser', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'wallet', type: 'address' },
      ],
      name: 'isListed',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'module', type: 'address' },
      ],
      name: 'isModuleListed',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'listCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
      name: 'supportsInterface',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    { stateMutability: 'payable', type: 'receive' },
  ],
} as const
