export default {
  version: '1.0.0',
  contractName: 'PalmeraModule',
  abi: [
    {
      inputs: [
        { internalType: 'address', name: 'authorityAddress', type: 'address' },
        { internalType: 'address', name: '_palmeraGuard', type: 'address' },
        { internalType: 'uint256', name: 'maxDepthLimitInitial', type: 'uint256' },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'AddresNotAllowed', type: 'error' },
    { inputs: [], name: 'AddressDenied', type: 'error' },
    {
      inputs: [{ internalType: 'uint256', name: 'children', type: 'uint256' }],
      name: 'CannotRemoveSafeBeforeRemoveChild',
      type: 'error',
    },
    { inputs: [], name: 'DenyHelpersDisabled', type: 'error' },
    {
      inputs: [
        { internalType: 'uint256', name: 'treeLimit', type: 'uint256' },
        { internalType: 'uint256', name: 'widthLimit', type: 'uint256' },
      ],
      name: 'DepthLimitReached',
      type: 'error',
    },
    { inputs: [], name: 'EmptyName', type: 'error' },
    { inputs: [], name: 'InvalidAddressProvided', type: 'error' },
    { inputs: [], name: 'InvalidLimit', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'safe', type: 'address' }], name: 'InvalidRootSafe', type: 'error' },
    { inputs: [], name: 'InvalidSafeId', type: 'error' },
    { inputs: [], name: 'ListEmpty', type: 'error' },
    { inputs: [], name: 'NotAuthorizedAddOrRemovedOwner', type: 'error' },
    { inputs: [], name: 'NotAuthorizedDisableModuleOrGuard', type: 'error' },
    { inputs: [], name: 'NotAuthorizedDisconnectChildrenSafe', type: 'error' },
    { inputs: [], name: 'NotAuthorizedSetRole', type: 'error' },
    { inputs: [], name: 'NotAuthorizedUpdateNonSuperSafe', type: 'error' },
    { inputs: [], name: 'NotAuthorizedUpdateSafeToOtherOrg', type: 'error' },
    { inputs: [], name: 'NotPermittedReceiveEther', type: 'error' },
    {
      inputs: [{ internalType: 'bytes32', name: 'org', type: 'bytes32' }],
      name: 'OrgAlreadyRegistered',
      type: 'error',
    },
    { inputs: [{ internalType: 'bytes32', name: 'org', type: 'bytes32' }], name: 'OrgNotRegistered', type: 'error' },
    { inputs: [], name: 'OwnerAlreadyExists', type: 'error' },
    { inputs: [], name: 'OwnerNotFound', type: 'error' },
    {
      inputs: [{ internalType: 'address', name: 'safe', type: 'address' }],
      name: 'PreviewModuleNotFound',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'address', name: 'safe', type: 'address' }],
      name: 'SafeAlreadyRegistered',
      type: 'error',
    },
    { inputs: [], name: 'SafeAlreadyRemoved', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'safe', type: 'address' }], name: 'SafeIdInvalidated', type: 'error' },
    {
      inputs: [{ internalType: 'uint256', name: 'safe', type: 'uint256' }],
      name: 'SafeIdNotRegistered',
      type: 'error',
    },
    { inputs: [{ internalType: 'address', name: 'safe', type: 'address' }], name: 'SafeNotRegistered', type: 'error' },
    {
      inputs: [{ internalType: 'enum DataTypes.Role', name: 'role', type: 'uint8' }],
      name: 'SetRoleForbidden',
      type: 'error',
    },
    { inputs: [], name: 'TxExecutionModuleFailed', type: 'error' },
    { inputs: [], name: 'TxOnBehalfExecutedFailed', type: 'error' },
    { inputs: [], name: 'UserAlreadyOnList', type: 'error' },
    { inputs: [], name: 'ZeroAddressProvided', type: 'error' },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address[]', name: 'users', type: 'address[]' }],
      name: 'AddedToList',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'user', type: 'address' },
        { indexed: true, internalType: 'contract Authority', name: 'newAuthority', type: 'address' },
      ],
      name: 'AuthorityUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'address', name: 'user', type: 'address' }],
      name: 'DroppedFromList',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'rootSafeId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'updater', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'oldTreeLimit', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'newTreeLimit', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'oldWidthLimit', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'newWidthLimit', type: 'uint256' },
      ],
      name: 'NewLimitLevel',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      ],
      name: 'OrganisationCreated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'user', type: 'address' },
        { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
      ],
      name: 'OwnerUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'newIdRootSafe', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'updater', type: 'address' },
        { indexed: false, internalType: 'address', name: 'newRootSafe', type: 'address' },
        { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      ],
      name: 'RootSafePromoted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'safeCreated', type: 'uint256' },
        { indexed: false, internalType: 'address', name: 'lead', type: 'address' },
        { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'superSafe', type: 'uint256' },
        { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      ],
      name: 'SafeCreated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'safe', type: 'address' },
        { indexed: false, internalType: 'address', name: 'disconnector', type: 'address' },
      ],
      name: 'SafeDisconnected',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'Invalidator', type: 'address' },
      ],
      name: 'SafeInvalidated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'safeRemoved', type: 'uint256' },
        { indexed: false, internalType: 'address', name: 'lead', type: 'address' },
        { indexed: true, internalType: 'address', name: 'remover', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'superSafe', type: 'uint256' },
        { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      ],
      name: 'SafeRemoved',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'safeUpdated', type: 'uint256' },
        { indexed: false, internalType: 'address', name: 'lead', type: 'address' },
        { indexed: true, internalType: 'address', name: 'updater', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'oldSuperSafe', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'newSuperSafe', type: 'uint256' },
      ],
      name: 'SafeSuperUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'address', name: 'executor', type: 'address' },
        { indexed: false, internalType: 'address', name: 'superSafe', type: 'address' },
        { indexed: true, internalType: 'address', name: 'target', type: 'address' },
        { indexed: false, internalType: 'bool', name: 'result', type: 'bool' },
      ],
      name: 'TxOnBehalfExecuted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'user', type: 'address' },
        { indexed: true, internalType: 'address', name: 'updater', type: 'address' },
        { indexed: true, internalType: 'uint8', name: 'role', type: 'uint8' },
        { indexed: false, internalType: 'bool', name: 'enabled', type: 'bool' },
      ],
      name: 'UserRoleUpdatedByOrg',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { indexed: true, internalType: 'uint256', name: 'rootSafeId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'remover', type: 'address' },
        { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      ],
      name: 'WholeTreeRemoved',
      type: 'event',
    },
    { stateMutability: 'nonpayable', type: 'fallback' },
    {
      inputs: [],
      name: 'NAME',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'VERSION',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address[]', name: 'modules', type: 'address[]' }],
      name: 'addExternalModules',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'ownerAdded', type: 'address' },
        { internalType: 'uint256', name: 'threshold', type: 'uint256' },
        { internalType: 'address', name: 'targetSafe', type: 'address' },
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
      ],
      name: 'addOwnerWithThreshold',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'superSafeId', type: 'uint256' },
        { internalType: 'string', name: 'name', type: 'string' },
      ],
      name: 'addSafe',
      outputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address[]', name: 'users', type: 'address[]' }],
      name: 'addToList',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'allowFeature',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'allowedSafeRoles',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'authority',
      outputs: [{ internalType: 'contract Authority', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'denyFeature',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'depthTreeLimit',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'depthWidthLimit',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    { inputs: [], name: 'disableDenyHelper', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
      inputs: [
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { internalType: 'uint256', name: 'pagesize', type: 'uint256' },
      ],
      name: 'disconnectSafe',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'uint8', name: 'role', type: 'uint8' },
      ],
      name: 'doesUserHaveRole',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'domainSeparator',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'module', type: 'address' },
        { internalType: 'uint256', name: 'pagesize', type: 'uint256' },
      ],
      name: 'dropExternalModules',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
      name: 'dropFromList',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    { inputs: [], name: 'enableAllowlist', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'enableDenylist', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'superSafe', type: 'address' },
        { internalType: 'address', name: 'targetSafe', type: 'address' },
        { internalType: 'address', name: 'to', type: 'address' },
        { internalType: 'uint256', name: 'value', type: 'uint256' },
        { internalType: 'bytes', name: 'data', type: 'bytes' },
        { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      ],
      name: 'encodeTransactionData',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'superSafe', type: 'address' },
        { internalType: 'address', name: 'targetSafe', type: 'address' },
        { internalType: 'address', name: 'to', type: 'address' },
        { internalType: 'uint256', name: 'value', type: 'uint256' },
        { internalType: 'bytes', name: 'data', type: 'bytes' },
        { internalType: 'bytes', name: 'signatures', type: 'bytes' },
      ],
      name: 'execTransactionOnBehalf',
      outputs: [{ internalType: 'bool', name: 'result', type: 'bool' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getChainId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'getOrgBySafe',
      outputs: [{ internalType: 'bytes32', name: 'orgSafe', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'safe', type: 'address' }],
      name: 'getOrgHashBySafe',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'wallet', type: 'address' },
      ],
      name: 'getPrevUser',
      outputs: [{ internalType: 'address', name: 'prevUser', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'getRootSafe',
      outputs: [{ internalType: 'uint256', name: 'rootSafeId', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'getSafeAddress',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'safe', type: 'address' },
      ],
      name: 'getSafeIdBySafe',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'getSafeInfo',
      outputs: [
        { internalType: 'enum DataTypes.Tier', name: '', type: 'uint8' },
        { internalType: 'string', name: '', type: 'string' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256[]', name: '', type: 'uint256[]' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'superSafe', type: 'address' },
        { internalType: 'address', name: 'targetSafe', type: 'address' },
        { internalType: 'address', name: 'to', type: 'address' },
        { internalType: 'uint256', name: 'value', type: 'uint256' },
        { internalType: 'bytes', name: 'data', type: 'bytes' },
        { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      ],
      name: 'getTransactionHash',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'caller', type: 'address' },
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'targetSafe', type: 'address' },
      ],
      name: 'hasNotPermissionOverTarget',
      outputs: [{ internalType: 'bool', name: 'hasNotPermission', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'indexId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: '', type: 'bytes32' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'indexSafe',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'invalidateSafe',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: '', type: 'bytes32' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'invalidatedSafeId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'superSafeId', type: 'uint256' }],
      name: 'isLimitReached',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
        { internalType: 'address', name: 'wallet', type: 'address' },
      ],
      name: 'isListed',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: 'org', type: 'bytes32' }],
      name: 'isOrgRegistered',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'rootSafeId', type: 'uint256' },
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
      ],
      name: 'isPendingRemove',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'root', type: 'address' },
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
      ],
      name: 'isRootSafeOf',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'safe', type: 'address' }],
      name: 'isSafe',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'bool', name: 'checkModifyOwners', type: 'bool' },
        { internalType: 'bool', name: 'checkExecOnBehalf', type: 'bool' },
      ],
      name: 'isSafeLead',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'safe', type: 'address' }],
      name: 'isSafeRegistered',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'superSafeId', type: 'uint256' },
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
      ],
      name: 'isSuperSafe',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'superSafeId', type: 'uint256' },
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
      ],
      name: 'isTreeMember',
      outputs: [{ internalType: 'bool', name: 'isMember', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'listCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      name: 'orgNonce',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'promoteRoot',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'string', name: 'orgName', type: 'string' }],
      name: 'registerOrg',
      outputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'prevOwner', type: 'address' },
        { internalType: 'address', name: 'ownerRemoved', type: 'address' },
        { internalType: 'uint256', name: 'threshold', type: 'uint256' },
        { internalType: 'address', name: 'targetSafe', type: 'address' },
        { internalType: 'bytes32', name: 'org', type: 'bytes32' },
      ],
      name: 'removeOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'safeId', type: 'uint256' }],
      name: 'removeSafe',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'pagesize', type: 'uint256' }],
      name: 'removeWholeTree',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes32', name: '', type: 'bytes32' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'safesInfoByOrg',
      outputs: [
        { internalType: 'enum DataTypes.Tier', name: 'tier', type: 'uint8' },
        { internalType: 'string', name: 'name', type: 'string' },
        { internalType: 'address', name: 'lead', type: 'address' },
        { internalType: 'address', name: 'safe', type: 'address' },
        { internalType: 'uint256', name: 'superSafe', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'setter', type: 'address' },
        { internalType: 'bool', name: 'enable', type: 'bool' },
      ],
      name: 'setAllowedSafeRoles',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'contract Authority', name: 'newAuthority', type: 'address' }],
      name: 'setAuthority',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      name: 'setOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'enum DataTypes.Role', name: 'role', type: 'uint8' },
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { internalType: 'bool', name: 'enabled', type: 'bool' },
      ],
      name: 'setRole',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'newDeepLimit', type: 'uint256' },
        { internalType: 'uint256', name: 'newWidthLimit', type: 'uint256' },
      ],
      name: 'updateDepthLimits',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'safeId', type: 'uint256' },
        { internalType: 'uint256', name: 'newSuperId', type: 'uint256' },
      ],
      name: 'updateSuper',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    { stateMutability: 'payable', type: 'receive' },
  ],
} as const
